config/routes.rb
Mobilepres::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "home/index"

  resources :photos

  resources :collections

  resources :products

  resources :statues

  devise_for :users

  root :to => 'home#index'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  attr_accessible :name
  has_many :products
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @collections = Collection.all
  end

  def show
    @collection = Collection.find(params[:id])
    @products = @collection.products
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(params[:collection])
    if @collection.save
      redirect_to @collection, :notice => "Successfully created collection."
    else
      render :action => 'new'
    end
  end

  def edit
    @collection = Collection.find(params[:id])
  end

  def update
    @collection = Collection.find(params[:id])
    if @collection.update_attributes(params[:collection])
      redirect_to @collection, :notice  => "Successfully updated collection."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy
    redirect_to collections_url, :notice => "Successfully destroyed collection."
  end

  def list
    @collections = Collection.all
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_for @collection do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/collections/edit.html.erb
<% title "Edit Collection" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @collection %> |
  <%= link_to "View All", collections_path %>
</p>

app/views/collections/index.html.erb
<% title "Collections" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for collection in @collections %>
    <tr>
      <td><%= collection.name %></td>
      <td><%= link_to "Show", collection %></td>
      <td><%= link_to "Edit", edit_collection_path(collection) %></td>
      <td><%= link_to "Destroy", collection, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Collection", new_collection_path %></p>

app/views/collections/new.html.erb
<% title "New Collection" %>

<%= render 'form' %>

<p><%= link_to "Back to List", collections_path %></p>

app/views/collections/show.html.erb
<% title "Collection" %>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

Is there <b><%= pluralize(@products.count, 'product') %></b> in this collection.
<table>
<% @products.each do |p| %>
<tr>
	<td><%= link_to p.name, product_path(p) %></td>
	<td><%= p.description %></td>
	<td><%= p.statue.name %></td>
	<% p.photos.each do |img| %>
		<td><%= image_tag img.image_url(:thumb).to_s %></td>
	<% end %>
</tr>	
<% end %>
</table>
<p>
	<%= link_to 'Back', :back %>
</p>