config/routes.rb
Mobilepres::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "home/index"

  resources :photos

  resources :collections

  resources :products

  resources :statues

  devise_for :users

  root :to => 'home#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :image, :product_id
  belongs_to :product
  mount_uploader :image, PhotoUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(params[:photo])
    if @photo.save
      redirect_to @photo, :notice => "Successfully created photo."
    else
      render :action => 'new'
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(params[:photo])
      redirect_to @photo, :notice  => "Successfully updated photo."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_url, :notice => "Successfully destroyed photo."
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for @photo do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </p>
  <p>
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/photos/edit.html.erb
<% title "Edit Photo" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @photo %> |
  <%= link_to "View All", photos_path %>
</p>

app/views/photos/index.html.erb
<% title "Photos" %>

<table>
  <tr>
    <th>Image</th>
    <th>Product</th>
  </tr>
  <% for photo in @photos %>
    <tr>
      <td><%= photo.image %></td>
      <td><%= photo.product_id %></td>
      <td><%= link_to "Show", photo %></td>
      <td><%= link_to "Edit", edit_photo_path(photo) %></td>
      <td><%= link_to "Destroy", photo, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Photo", new_photo_path %></p>

app/views/photos/new.html.erb
<% title "New Photo" %>

<%= render 'form' %>

<p><%= link_to "Back to List", photos_path %></p>

app/views/photos/show.html.erb
<% title "Photo" %>

<p>
  <strong>Image:</strong>
  <%= @photo.image %>
</p>
<p>
  <strong>Product:</strong>
  <%= @photo.product_id %>
</p>

<p>
	<%= link_to 'Back', :back %>
</p>