config/routes.rb
Mobilepres::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "home/index"

  resources :photos

  resources :collections

  resources :products

  resources :statues

  devise_for :users

  root :to => 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :description, :collection_id, :statue_id, :photos_attributes
  belongs_to :statue
  belongs_to :collection
  has_many :photos
  accepts_nested_attributes_for :photos,  :allow_destroy => true, :reject_if => :all_blank
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    min = 0
    count = 50
    if params[:min] then min = params[:min].to_i end
    if params[:count] then count = params[:count].to_i end
    if params[:statue_id] then statue_id = params[:statue_id].to_i end
    if params[:cat_id] then col_id = params[:cat_id].to_i end
    @products = Product.offset(min).limit(count)
    if col_id
      @products = @products.where(:collection_id => col_id) if col_id
    end
    if statue_id != 0
      @products = @products.where(:statue_id => statue_id) if statue_id
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to @product, :notice => "Successfully created product."
    else
      render :action => 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product, :notice  => "Successfully updated product."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, :notice => "Successfully destroyed product."
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :collection_id %><br />
    <%= f.number_field :collection_id %>
  </p>
  <p>
    <%= f.label :statue_id %><br />
    <%= f.number_field :statue_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/products/edit.html.erb
<% title "Edit Product" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @product %> |
  <%= link_to "View All", products_path %>
</p>

app/views/products/index.html.erb
<% title "Products" %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Collection</th>
    <th>Statue</th>
  </tr>
  <% for product in @products %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= product.collection_id %></td>
      <td><%= product.statue_id %></td>
      <td><%= link_to "Show", product %></td>
      <td><%= link_to "Edit", edit_product_path(product) %></td>
      <td><%= link_to "Destroy", product, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Product", new_product_path %></p>

app/views/products/new.html.erb
<% title "New Product" %>

<%= render 'form' %>

<p><%= link_to "Back to List", products_path %></p>

app/views/products/show.html.erb
<% title "Product" %>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Collection:</strong>
  <%= @product.collection.name %>
</p>
<p>
  <strong>Statue:</strong>
  <%= @product.statue.name %>
</p>

<% @product.photos.each do |p| %>
	<%= image_tag p.image_url(:big) %> </br>
<% end %>

<p>

	<%= link_to 'Back', :back %>
</p>